version: '3.1'

services:

  mysql-transactions:
    container_name: mysql-transactions
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: transactionsdb
      MYSQL_ROOT_PASSWORD: minhaSenhaForte
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data_container:/data/db

volumes:
    mysql_data_container: